# Generated by Django 3.2.4 on 2021-06-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_sale_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watercraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество товара на складе')),
                ('discountPrice', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('dateSold', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('madiIn', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('place', models.IntegerField(verbose_name='Количество мест')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('motor', models.CharField(max_length=255, verbose_name='Тип двигателя')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='productSale',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
