# Generated by Django 3.2.4 on 2021-06-20 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20210618_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='media/images/')),
                ('model', models.CharField(max_length=255, verbose_name='Название подели')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество товара на складе')),
                ('discountPrice', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('dateSold', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('made', models.DateField(blank=True, null=True, verbose_name='Прозведено')),
                ('madeIn', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность')),
                ('motor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='media/avatar/')),
                ('izbrannye', models.ManyToManyField(blank=True, null=True, to='shop.Product', verbose_name='Избранные')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0),
        ),
        migrations.DeleteModel(
            name='Watercraft',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория продукта'),
        ),
    ]
