# Generated by Django 3.2.4 on 2021-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='empty',
            field=models.CharField(blank=True, default='Закончилось', editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='izbrannye',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Product', verbose_name='Корзина'),
        ),
    ]
